#!/usr/bin/env bash
#
# Generate the key material the service itself needs, for local development:
#
#   <dir>/jwt.key                   EC P-256 private key -- signs every token
#   <dir>/jwt.pub                   its public half -- verifies every token
#   <dir>/aes-256-symmetric-hex.key 32 random bytes, hex-encoded -- encrypts
#                                   IdP client secrets at rest
#   <dir>/<host>.crt, <dir>/<host>.key
#                                   a self-signed TLS pair for the HTTP server
#                                   itself; <host> defaults to goapitemplate.local
#
# The first three are the settings with no working default (authn.private.key.file,
# authn.public.key.file, authn.symmetric.key.file). The fourth exists because
# .air.toml and run.sh name http.server.tls.cert.file and .key.file, and a
# file-valued flag is OPENED while the flags are parsed -- so a fresh checkout
# refused to start with "invalid value ... no such file or directory" before
# reading anything else, even with http.server.tls.enabled=false. Every path
# the dev stack names must exist after `make dev-certs`, and
# TestEveryDevStackCertIsGenerated fails if one is added that this script and
# generate-dev-certs.sh do not produce. The TLS material for PostgreSQL and
# Valkey is a separate concern, generated by generate-dev-certs.sh.
#
# Idempotent, and it NEVER overwrites:
#
#   - a new jwt.key invalidates every token the running service has issued;
#   - a new AES key makes every secret already encrypted with the old one
#     unreadable, with no error until something tries to decrypt it.
#
# To rotate on purpose, delete the file and run again. jwt.pub is derived, so
# deleting only the public half re-derives it from the private key that is there.
#
# Usage: generate-dev-keys.sh <output-directory> [server-host]

set -euo pipefail

OUT="${1:?usage: generate-dev-keys.sh <output-directory> [server-host]}"
HOST="${2:-goapitemplate.local}"

mkdir -p "$OUT"

if [ -f "$OUT/jwt.key" ]; then
  echo "  $OUT/jwt.key is present, keeping it"
else
  echo "  generating the JWT signing key (EC prime256v1): $OUT/jwt.key"
  openssl ecparam -genkey -name prime256v1 -noout -out "$OUT/jwt.key" 2>/dev/null
  chmod 600 "$OUT/jwt.key"
fi

if [ -f "$OUT/jwt.pub" ]; then
  echo "  $OUT/jwt.pub is present, keeping it"
else
  echo "  deriving the JWT public key: $OUT/jwt.pub"
  openssl ec -in "$OUT/jwt.key" -pubout -out "$OUT/jwt.pub" 2>/dev/null
  chmod 644 "$OUT/jwt.pub"
fi

# A pair that does not match is fatal at startup ("PublicKey is not the public
# half of PrivateKey"). Say so here, where the fix is one deleted file away.
if ! diff -q <(openssl ec -in "$OUT/jwt.key" -pubout 2>/dev/null) "$OUT/jwt.pub" >/dev/null 2>&1; then
  echo "  WARNING: $OUT/jwt.pub is not the public half of $OUT/jwt.key; the service will refuse to start." >&2
  echo "           Delete $OUT/jwt.pub and run again to re-derive it." >&2
fi

if [ -f "$OUT/aes-256-symmetric-hex.key" ]; then
  echo "  $OUT/aes-256-symmetric-hex.key is present, keeping it"
else
  echo "  generating the AES-256 key (64 hex characters): $OUT/aes-256-symmetric-hex.key"
  openssl rand -hex 32 | tr -d '\n' > "$OUT/aes-256-symmetric-hex.key"
  chmod 600 "$OUT/aes-256-symmetric-hex.key"
fi

# AES takes exactly 16, 24 or 32 bytes: 32, 48 or 64 hex characters in the
# file. The service refuses any other length at startup, naming the setting.
case "$(tr -d '\n' < "$OUT/aes-256-symmetric-hex.key" | wc -c | tr -d ' ')" in
  32|48|64) ;;
  *) echo "  WARNING: $OUT/aes-256-symmetric-hex.key must hold 32, 48 or 64 hex characters; the service will refuse to start." >&2 ;;
esac

# The HTTP server's own TLS pair, self-signed: nothing verifies it but a browser
# or curl -k, and the dev stack runs with http.server.tls.enabled=false anyway --
# the files only have to EXIST, because the flags that name them open them.
# Regenerated only when missing or expired, like the database certificates.
if [ -f "$OUT/$HOST.crt" ] && [ -f "$OUT/$HOST.key" ] && openssl x509 -checkend 86400 -noout -in "$OUT/$HOST.crt" >/dev/null 2>&1; then
  echo "  $OUT/$HOST.crt is present and valid, keeping it"
else
  echo "  generating the HTTP server TLS pair (self-signed, EC prime256v1): $OUT/$HOST.{crt,key}"
  openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 -nodes -sha256 -days 365 \
    -keyout "$OUT/$HOST.key" -out "$OUT/$HOST.crt" \
    -subj "/CN=$HOST" \
    -addext "subjectAltName = DNS:$HOST, DNS:localhost, IP:127.0.0.1" 2>/dev/null
  chmod 600 "$OUT/$HOST.key"
  chmod 644 "$OUT/$HOST.crt"
fi

echo "  done: $(basename "$OUT")/{jwt.key,jwt.pub,aes-256-symmetric-hex.key,$HOST.crt,$HOST.key}"
