// Code generated by MockGen. DO NOT EDIT.
// Source: authn_idp.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../mocks/handler/authn_idp.go -source=authn_idp.go AuthnIDPs
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthnIDPs is a mock of AuthnIDPs interface.
type MockAuthnIDPs struct {
	ctrl     *gomock.Controller
	recorder *MockAuthnIDPsMockRecorder
	isgomock struct{}
}

// MockAuthnIDPsMockRecorder is the mock recorder for MockAuthnIDPs.
type MockAuthnIDPsMockRecorder struct {
	mock *MockAuthnIDPs
}

// NewMockAuthnIDPs creates a new mock instance.
func NewMockAuthnIDPs(ctrl *gomock.Controller) *MockAuthnIDPs {
	mock := &MockAuthnIDPs{ctrl: ctrl}
	mock.recorder = &MockAuthnIDPsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthnIDPs) EXPECT() *MockAuthnIDPsMockRecorder {
	return m.recorder
}

// Callback mocks base method.
func (m *MockAuthnIDPs) Callback(ctx context.Context, idpID uuid.UUID, state, code string) (*domain.IDPCallbackOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Callback", ctx, idpID, state, code)
	ret0, _ := ret[0].(*domain.IDPCallbackOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Callback indicates an expected call of Callback.
func (mr *MockAuthnIDPsMockRecorder) Callback(ctx, idpID, state, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Callback", reflect.TypeOf((*MockAuthnIDPs)(nil).Callback), ctx, idpID, state, code)
}

// GetLoginURL mocks base method.
func (m *MockAuthnIDPs) GetLoginURL(ctx context.Context, idpID uuid.UUID, eventType domain.IDPEventType, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginURL", ctx, idpID, eventType, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginURL indicates an expected call of GetLoginURL.
func (mr *MockAuthnIDPsMockRecorder) GetLoginURL(ctx, idpID, eventType, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginURL", reflect.TypeOf((*MockAuthnIDPs)(nil).GetLoginURL), ctx, idpID, eventType, userID)
}

// ListIdentities mocks base method.
func (m *MockAuthnIDPs) ListIdentities(ctx context.Context, userID uuid.UUID) ([]domain.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIdentities", ctx, userID)
	ret0, _ := ret[0].([]domain.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIdentities indicates an expected call of ListIdentities.
func (mr *MockAuthnIDPsMockRecorder) ListIdentities(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIdentities", reflect.TypeOf((*MockAuthnIDPs)(nil).ListIdentities), ctx, userID)
}

// UnlinkIdentity mocks base method.
func (m *MockAuthnIDPs) UnlinkIdentity(ctx context.Context, userID, idpID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkIdentity", ctx, userID, idpID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkIdentity indicates an expected call of UnlinkIdentity.
func (mr *MockAuthnIDPsMockRecorder) UnlinkIdentity(ctx, userID, idpID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkIdentity", reflect.TypeOf((*MockAuthnIDPs)(nil).UnlinkIdentity), ctx, userID, idpID)
}
