// Code generated by MockGen. DO NOT EDIT.
// Source: rate_limits.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../mocks/handler/rate_limits.go -source=rate_limits.go RateLimits
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRateLimits is a mock of RateLimits interface.
type MockRateLimits struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimitsMockRecorder
	isgomock struct{}
}

// MockRateLimitsMockRecorder is the mock recorder for MockRateLimits.
type MockRateLimitsMockRecorder struct {
	mock *MockRateLimits
}

// NewMockRateLimits creates a new mock instance.
func NewMockRateLimits(ctrl *gomock.Controller) *MockRateLimits {
	mock := &MockRateLimits{ctrl: ctrl}
	mock.recorder = &MockRateLimitsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimits) EXPECT() *MockRateLimitsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRateLimits) Create(ctx context.Context, input *domain.CreateRateLimitInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRateLimitsMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRateLimits)(nil).Create), ctx, input)
}

// DeleteByID mocks base method.
func (m *MockRateLimits) DeleteByID(ctx context.Context, input *domain.DeleteRateLimitInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockRateLimitsMockRecorder) DeleteByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockRateLimits)(nil).DeleteByID), ctx, input)
}

// Effective mocks base method.
func (m *MockRateLimits) Effective(ctx context.Context, req domain.RateLimitRequest) ([]domain.RateLimitMatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Effective", ctx, req)
	ret0, _ := ret[0].([]domain.RateLimitMatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Effective indicates an expected call of Effective.
func (mr *MockRateLimitsMockRecorder) Effective(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Effective", reflect.TypeOf((*MockRateLimits)(nil).Effective), ctx, req)
}

// Enforcing mocks base method.
func (m *MockRateLimits) Enforcing() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforcing")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enforcing indicates an expected call of Enforcing.
func (mr *MockRateLimitsMockRecorder) Enforcing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforcing", reflect.TypeOf((*MockRateLimits)(nil).Enforcing))
}

// GetByID mocks base method.
func (m *MockRateLimits) GetByID(ctx context.Context, id uuid.UUID) (*domain.RateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.RateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRateLimitsMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRateLimits)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockRateLimits) List(ctx context.Context, input *domain.SelectRateLimitsInput) (*domain.ListRateLimitsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, input)
	ret0, _ := ret[0].(*domain.ListRateLimitsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRateLimitsMockRecorder) List(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRateLimits)(nil).List), ctx, input)
}

// UpdateByID mocks base method.
func (m *MockRateLimits) UpdateByID(ctx context.Context, input *domain.UpdateRateLimitInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockRateLimitsMockRecorder) UpdateByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockRateLimits)(nil).UpdateByID), ctx, input)
}
