// Code generated by MockGen. DO NOT EDIT.
// Source: roles.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../mocks/handler/roles.go -source=roles.go Roles
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRoles is a mock of Roles interface.
type MockRoles struct {
	ctrl     *gomock.Controller
	recorder *MockRolesMockRecorder
	isgomock struct{}
}

// MockRolesMockRecorder is the mock recorder for MockRoles.
type MockRolesMockRecorder struct {
	mock *MockRoles
}

// NewMockRoles creates a new mock instance.
func NewMockRoles(ctrl *gomock.Controller) *MockRoles {
	mock := &MockRoles{ctrl: ctrl}
	mock.recorder = &MockRolesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoles) EXPECT() *MockRolesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoles) Create(ctx context.Context, input *domain.CreateRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRolesMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoles)(nil).Create), ctx, input)
}

// DeleteByID mocks base method.
func (m *MockRoles) DeleteByID(ctx context.Context, input *domain.DeleteRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockRolesMockRecorder) DeleteByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockRoles)(nil).DeleteByID), ctx, input)
}

// GetByID mocks base method.
func (m *MockRoles) GetByID(ctx context.Context, id uuid.UUID) (*domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRolesMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRoles)(nil).GetByID), ctx, id)
}

// LinkPolicies mocks base method.
func (m *MockRoles) LinkPolicies(ctx context.Context, input *domain.LinkPoliciesToRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkPolicies", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkPolicies indicates an expected call of LinkPolicies.
func (mr *MockRolesMockRecorder) LinkPolicies(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkPolicies", reflect.TypeOf((*MockRoles)(nil).LinkPolicies), ctx, input)
}

// LinkUsers mocks base method.
func (m *MockRoles) LinkUsers(ctx context.Context, input *domain.LinkUsersToRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkUsers", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkUsers indicates an expected call of LinkUsers.
func (mr *MockRolesMockRecorder) LinkUsers(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkUsers", reflect.TypeOf((*MockRoles)(nil).LinkUsers), ctx, input)
}

// List mocks base method.
func (m *MockRoles) List(ctx context.Context, input *domain.ListRolesInput) (*domain.ListRolesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, input)
	ret0, _ := ret[0].(*domain.ListRolesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRolesMockRecorder) List(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoles)(nil).List), ctx, input)
}

// ListByPolicyID mocks base method.
func (m *MockRoles) ListByPolicyID(ctx context.Context, policyID uuid.UUID, input *domain.ListRolesInput) (*domain.ListRolesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPolicyID", ctx, policyID, input)
	ret0, _ := ret[0].(*domain.ListRolesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPolicyID indicates an expected call of ListByPolicyID.
func (mr *MockRolesMockRecorder) ListByPolicyID(ctx, policyID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPolicyID", reflect.TypeOf((*MockRoles)(nil).ListByPolicyID), ctx, policyID, input)
}

// ListByUserID mocks base method.
func (m *MockRoles) ListByUserID(ctx context.Context, userID uuid.UUID, input *domain.ListRolesInput) (*domain.ListRolesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, input)
	ret0, _ := ret[0].(*domain.ListRolesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockRolesMockRecorder) ListByUserID(ctx, userID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockRoles)(nil).ListByUserID), ctx, userID, input)
}

// UnlinkPolicies mocks base method.
func (m *MockRoles) UnlinkPolicies(ctx context.Context, input *domain.UnlinkPoliciesFromRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkPolicies", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkPolicies indicates an expected call of UnlinkPolicies.
func (mr *MockRolesMockRecorder) UnlinkPolicies(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkPolicies", reflect.TypeOf((*MockRoles)(nil).UnlinkPolicies), ctx, input)
}

// UnlinkUsers mocks base method.
func (m *MockRoles) UnlinkUsers(ctx context.Context, input *domain.UnlinkUsersFromRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkUsers", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkUsers indicates an expected call of UnlinkUsers.
func (mr *MockRolesMockRecorder) UnlinkUsers(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkUsers", reflect.TypeOf((*MockRoles)(nil).UnlinkUsers), ctx, input)
}

// UpdateByID mocks base method.
func (m *MockRoles) UpdateByID(ctx context.Context, input *domain.UpdateRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockRolesMockRecorder) UpdateByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockRoles)(nil).UpdateByID), ctx, input)
}
