// Code generated by MockGen. DO NOT EDIT.
// Source: token_lifetimes.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../mocks/handler/token_lifetimes.go -source=token_lifetimes.go TokenLifetimes
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenLifetimes is a mock of TokenLifetimes interface.
type MockTokenLifetimes struct {
	ctrl     *gomock.Controller
	recorder *MockTokenLifetimesMockRecorder
	isgomock struct{}
}

// MockTokenLifetimesMockRecorder is the mock recorder for MockTokenLifetimes.
type MockTokenLifetimesMockRecorder struct {
	mock *MockTokenLifetimes
}

// NewMockTokenLifetimes creates a new mock instance.
func NewMockTokenLifetimes(ctrl *gomock.Controller) *MockTokenLifetimes {
	mock := &MockTokenLifetimes{ctrl: ctrl}
	mock.recorder = &MockTokenLifetimesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenLifetimes) EXPECT() *MockTokenLifetimesMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTokenLifetimes) Get(ctx context.Context) (*domain.TokenLifetimes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(*domain.TokenLifetimes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTokenLifetimesMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTokenLifetimes)(nil).Get), ctx)
}

// Update mocks base method.
func (m *MockTokenLifetimes) Update(ctx context.Context, input *domain.UpdateTokenLifetimesInput) (*domain.TokenLifetimes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*domain.TokenLifetimes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTokenLifetimesMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTokenLifetimes)(nil).Update), ctx, input)
}
