-- +goose Up
-- +goose StatementBegin

-----------------------------------------------------------------------------------------
-- table roles
-----------------------------------------------------------------------------------------
INSERT INTO roles (id, name, description, system, auto_assign) VALUES
-- Administrator
('019822af-b448-750c-ae0d-edaf3aaafc41', 'Administrator', 'Administrator role.',                         TRUE, FALSE),
-- AuthenticatedUser
('019822af-b448-7514-a670-f7acef5d6f77', 'AuthenticatedUser', 'Authenticated user role. Allow do login', TRUE, TRUE);

-----------------------------------------------------------------------------------------
-- table resources
-----------------------------------------------------------------------------------------
INSERT INTO resources (id, name, description, action, resource, system) VALUES
-- full access
('019822af-b448-7520-a13a-edad1b3f4b93', 'Allow all', 'Allow all actions on all resources', '*', '*', TRUE),
-- all paths only GET
('019822af-b448-7524-995a-30d68b1263e8', 'Read only', 'Allow all GET action on all resources', 'GET', '*', TRUE),
-- all paths only POST
('019822af-b448-752c-ab03-9fd685db675d', 'Create only', 'Allow all POST action on all resources', 'POST', '*', TRUE),
-- all paths only DELETE
('019822af-b448-7534-921c-c22b7e26038f', 'Delete only', 'Allow all DELETE action on all resources', 'DELETE', '*', TRUE),
-- all paths only PUT
('019822af-b448-753b-9b02-e062d34ac1e9', 'Update only', 'Allow all PUT action on all resources',  'PUT', '*', TRUE),
-- all paths only PATCH
('019822af-b448-7543-968b-09af856a0bcf', 'Partial update only', 'Allow all PATCH action on all resources', 'PATCH', '*', TRUE),
-- all paths only OPTIONS
('019822af-b448-7547-b612-a26e449c4cdd', 'Options only', 'Allow all OPTIONS action on all resources', 'OPTIONS', '*', TRUE),
-- all paths only HEAD
('019822af-b448-754f-9014-027a5c1819b0', 'Head only', 'Allow all HEAD action on all resources', 'HEAD', '*', TRUE),
-- all paths only TRACE
('019822af-b448-7557-b71b-4f290da3139f', 'Trace only', 'Allow all TRACE action on all resources', 'TRACE', '*', TRUE),
-- automatic generate with the program apiendpoints
('0198fb33-7333-76f9-bcb4-1af086de3e10', 'List identity providers'             , 'Retrieve every ENABLED identity provider, for the login page. Disabled providers stay configured and are not offered'                                                                                                                                                                                                                   , 'GET'   , '/auth/idp/available'                         , TRUE    ),
('01988e60-89e5-72ee-9db4-db5cd7535717', 'Handle IDP OAuth callback'           , 'Called by the frontend callback route with the state and code from the provider, never by the browser: JSON answer, no cookie, no redirect. Spends the state, exchanges the code with PKCE, resolves the identity by subject'                                                                                                           , 'GET'   , '/auth/idp/{idp_id}/callback'                 , TRUE    ),
('01a07319-1d32-7bd2-8ba0-f7da9aaaed0a', 'Initiate IDP link'                   , 'Build the authorization URL for linking a provider identity to the signed-in account. The only way an existing account gains one: the session proves the account, the provider proves the identity'                                                                                                                                     , 'GET'   , '/auth/idp/{idp_id}/link'                     , TRUE    ),
('01988e60-89e5-72ab-adb4-3eef95d1afd3', 'Initiate IDP login'                  , 'Build the authorization URL for a sign-in. The caller sends the browser there; the provider returns it to the frontend callback route with a state and a code'                                                                                                                                                                          , 'GET'   , '/auth/idp/{idp_id}/login'                    , TRUE    ),
('019894ba-6014-79cf-bff4-6668484cc7e3', 'Initiate IDP registration'           , 'Build the authorization URL for a registration. Same flow as a login; the callback creates the account when the provider vouches for the email and allows auto-provisioning'                                                                                                                                                            , 'GET'   , '/auth/idp/{idp_id}/register'                 , TRUE    ),
('0198f1e2-14ff-7678-afbe-9a627b0eaabd', 'List IDP types'                      , 'Retrieve a paginated list of all Identity Provider Types available for authentication.'                                                                                                                                                                                                                                                 , 'GET'   , '/auth/idp_types'                             , TRUE    ),
('0198f1e2-14ff-767c-971c-3904e0f2c484', 'Get IDP type'                        , 'Retrieve a specific Identity Provider Type by its unique identifier'                                                                                                                                                                                                                                                                    , 'GET'   , '/auth/idp_types/{idp_type_id}'               , TRUE    ),
('0198e7ea-3755-7a29-90ed-13245b54f074', 'List IDPs'                           , 'Retrieve paginated list of Identity Providers with optional filtering and sorting'                                                                                                                                                                                                                                                      , 'GET'   , '/auth/idps'                                  , TRUE    ),
('0198e7ea-3755-7a39-9dfc-717d83facf02', 'Create IDP'                          , 'Register a new Identity Provider with authentication configuration'                                                                                                                                                                                                                                                                     , 'POST'  , '/auth/idps'                                  , TRUE    ),
('0198e7ea-3755-7a2d-9ab0-83ccef188e37', 'Delete IDP'                          , 'Permanently remove an Identity Provider configuration'                                                                                                                                                                                                                                                                                  , 'DELETE', '/auth/idps/{idp_id}'                         , TRUE    ),
('0198e7ea-3755-7a3d-8baa-36126e5d1c48', 'Get IDP'                             , 'Retrieve a specific Identity Provider configuration by its unique identifier'                                                                                                                                                                                                                                                           , 'GET'   , '/auth/idps/{idp_id}'                         , TRUE    ),
('0198e7ea-3755-7a35-9e30-6a9392e8e7a1', 'Update IDP'                          , 'Modify an existing Identity Provider configuration'                                                                                                                                                                                                                                                                                     , 'PUT'   , '/auth/idps/{idp_id}'                         , TRUE    ),
('019822af-b448-755b-92ff-d167d37719c2', 'Authenticate user'                   , 'Authenticate with email and password to obtain access and refresh tokens.'                                                                                                                                                                                                                                                              , 'POST'  , '/auth/login'                                 , TRUE    ),
('019822af-b448-7562-a27f-0d02884f3477', 'Logout user'                         , 'End the session. The access token this request was authorised with is revoked immediately and stops working. The refresh token is revoked too when it is supplied in the body -- without it, that token stays valid until it expires and can still mint new access tokens, so pass it.'                                                 , 'DELETE', '/auth/logout'                                , TRUE    ),
('01991917-2720-7589-971b-cce23bf8a74b', 'Initiate password recovery'          , 'Request a password reset email with secure token.'                                                                                                                                                                                                                                                                                      , 'POST'  , '/auth/password/recover'                      , TRUE    ),
('01991917-2720-758d-8104-94a0368acecb', 'Reset password'                      , 'Set new password using the token from password recovery email.'                                                                                                                                                                                                                                                                         , 'POST'  , '/auth/password/reset'                        , TRUE    ),
('019822af-b448-756a-92b2-791a0e748162', 'Refresh access token'                , 'Obtain new access and refresh tokens using valid refresh token. The token spent is the one in the Authorization header; the body is optional and, if it carries a token, it must be the same one.'                                                                                                                                      , 'POST'  , '/auth/refresh'                               , TRUE    ),
('019822af-b448-7572-a268-4c7b20a70229', 'Register new user'                   , 'Create a new user account and send verification email.'                                                                                                                                                                                                                                                                                 , 'POST'  , '/auth/register'                              , TRUE    ),
('01a072df-d81d-78c8-a72b-6ea167cd50b2', 'Get token lifetimes'                 , 'Read how long the access and refresh tokens issued from now on will live, the bounds a change is validated against, the shipped defaults, and who last changed them'                                                                                                                                                                    , 'GET'   , '/auth/token_lifetimes'                       , TRUE    ),
('01a072df-d81d-7995-ad3e-92a0a4d0a4cf', 'Update token lifetimes'              , 'Replace the access and refresh token lifetimes. Applies to tokens issued from now on; a token already issued keeps the expiry it was signed with. The change reaches every replica within its reload interval, or at once where a change signal is available'                                                                           , 'PUT'   , '/auth/token_lifetimes'                       , TRUE    ),
('019822af-b448-7576-8a41-41b83b3239f0', 'Resend verification email'           , 'Request a new verification email for unverified account.'                                                                                                                                                                                                                                                                               , 'POST'  , '/auth/verify'                                , TRUE    ),
('01a02dbb-bc41-7287-9cfd-7ac08bf882ae', 'Confirm email verification'          , 'Activate a user account with the verification token from the email. The token travels in the Authorization header, never in the URL.'                                                                                                                                                                                                   , 'POST'  , '/auth/verify/confirm'                        , TRUE    ),
('01982304-a1b2-7eec-8bf3-84f51fd09b74', 'Readiness probe and detailed health' , 'Per-component health, database pool stats and startup metrics, with the status code carrying the verdict: 200 healthy, 206 degraded, 503 a hard dependency is unreachable. This is the READINESS target — it answers whether this instance should receive traffic. Point liveness at /health/live, which deliberately checks nothing.'  , 'GET'   , '/health/detailed'                            , TRUE    ),
('01a02ec9-ac6c-77c2-81ad-d6e2f23bcd92', 'Liveness probe'                      , 'Answers 200 whenever this process can serve HTTP. It checks NOTHING else — no database, no cache — on purpose: a liveness probe decides whether to RESTART the process, and restarting cannot fix a dependency that is down. Point a readiness probe at /health/detailed instead, which does reflect dependencies.'                     , 'GET'   , '/health/live'                                , TRUE    ),
('0199489b-f2f0-718a-a0cb-de8752ea864f', 'Get authenticated user'              , 'Retrieve the profile information for the currently authenticated user'                                                                                                                                                                                                                                                                  , 'GET'   , '/me'                                         , TRUE    ),
('0199489b-f2f0-718e-a94d-b05a296eb818', 'Update authenticated user'           , 'Update the profile information for the currently authenticated user'                                                                                                                                                                                                                                                                    , 'PUT'   , '/me'                                         , TRUE    ),
('0199489b-f2f0-719e-b860-3b7ea6a86a1a', 'Get authorization info'              , 'Retrieve the authorization details and permissions for the currently authenticated user'                                                                                                                                                                                                                                                , 'GET'   , '/me/authz'                                   , TRUE    ),
('01a07319-1d32-7ca7-834a-d8dcc6a19fa0', 'List my linked identities'           , 'The identity providers the signed-in account can sign in through'                                                                                                                                                                                                                                                                       , 'GET'   , '/me/identities'                              , TRUE    ),
('01a07319-1d32-7cac-885b-6c544f5dbe08', 'Unlink my identity'                  , 'Remove the identity at one provider from the signed-in account. Refused when it is the only way into an account that has no password'                                                                                                                                                                                                   , 'DELETE', '/me/identities/{idp_id}'                     , TRUE    ),
('01a01117-dba9-74da-bd70-d1acc3842ffa', 'Get my resource limits'              , 'Retrieve the limits that apply to the calling user and how much of each has been consumed. Read-only: limits are not editable through the API.'                                                                                                                                                                                         , 'GET'   , '/me/resources_limits'                        , TRUE    ),
('01982303-f0f9-7ee4-968d-ba2078a272fc', 'List policies'                       , 'Retrieve a paginated list of all authorization policies in the system'                                                                                                                                                                                                                                                                  , 'GET'   , '/policies'                                   , TRUE    ),
('01982303-f0f9-7e38-ab68-486c8a2e819b', 'Create policy'                       , 'Create a new authorization policy with specified permissions'                                                                                                                                                                                                                                                                           , 'POST'  , '/policies'                                   , TRUE    ),
('01982303-f0f9-7f13-a03b-ed306ff7d06b', 'Delete policy'                       , 'Permanently remove an authorization policy by its unique identifier'                                                                                                                                                                                                                                                                    , 'DELETE', '/policies/{policy_id}'                       , TRUE    ),
('01982303-f0f9-7e30-ab3f-9220a73b02eb', 'Get policy'                          , 'Retrieve a specific authorization policy by its unique identifier'                                                                                                                                                                                                                                                                      , 'GET'   , '/policies/{policy_id}'                       , TRUE    ),
('01982303-f0f9-7ec1-8f39-98e77141c05c', 'Update policy'                       , 'Update an existing authorization policy by its unique identifier'                                                                                                                                                                                                                                                                       , 'PUT'   , '/policies/{policy_id}'                       , TRUE    ),
('01982303-f0f9-7ed4-9630-b9af3e3b6f17', 'Unlink roles from policy'            , 'Remove role associations from a specific policy'                                                                                                                                                                                                                                                                                        , 'DELETE', '/policies/{policy_id}/roles'                 , TRUE    ),
('01982303-f0f9-7ef0-ad95-3cb214216ef1', 'List roles by policy'                , 'Retrieve paginated list of roles associated with policy'                                                                                                                                                                                                                                                                                , 'GET'   , '/policies/{policy_id}/roles'                 , TRUE    ),
('01982303-f0f9-7e0d-ab27-f75b3a03ef46', 'Link roles to policy'                , 'Associate multiple roles with a specific policy for authorization'                                                                                                                                                                                                                                                                      , 'POST'  , '/policies/{policy_id}/roles'                 , TRUE    ),
('01982303-f0f9-7e63-92ba-141813745b06', 'List products'                       , 'List products across every project, with filtering, sorting, partial fields and pagination.'                                                                                                                                                                                                                                            , 'GET'   , '/products'                                   , TRUE    ),
('01982303-f0f9-7dbf-9688-6ef0150502e9', 'List projects'                       , 'Retrieve paginated list of accessible projects for authenticated user.'                                                                                                                                                                                                                                                                 , 'GET'   , '/projects'                                   , TRUE    ),
('01982303-f0f9-7e63-92ba-141813745a7d', 'Create project'                      , 'Create a new project with specified configuration.'                                                                                                                                                                                                                                                                                     , 'POST'  , '/projects'                                   , TRUE    ),
('01982303-f0f9-7e9f-9bb9-81d42a9eb30a', 'Delete project'                      , 'Permanently remove project and all associated data.'                                                                                                                                                                                                                                                                                    , 'DELETE', '/projects/{project_id}'                      , TRUE    ),
('01982303-f0f9-7dfa-966c-4b9ce4133a33', 'Get project'                         , 'Retrieve project details by unique identifier.'                                                                                                                                                                                                                                                                                         , 'GET'   , '/projects/{project_id}'                      , TRUE    ),
('01982303-f0f9-7db3-991f-2b7943b5328c', 'Update project'                      , 'Update existing project details by ID.'                                                                                                                                                                                                                                                                                                 , 'PUT'   , '/projects/{project_id}'                      , TRUE    ),
('01982303-f0f9-7e63-92ba-141813745b05', 'List products by project'            , 'List the products of one project, with filtering, sorting, partial fields and pagination.'                                                                                                                                                                                                                                              , 'GET'   , '/projects/{project_id}/products'             , TRUE    ),
('01982303-f0f9-7e63-92ba-141813745b01', 'Create product'                      , 'Create a new product inside a project. The name must be unique within the project.'                                                                                                                                                                                                                                                     , 'POST'  , '/projects/{project_id}/products'             , TRUE    ),
('01982303-f0f9-7e63-92ba-141813745b04', 'Delete product'                      , 'Delete a product from a project.'                                                                                                                                                                                                                                                                                                       , 'DELETE', '/projects/{project_id}/products/{product_id}', TRUE    ),
('01982303-f0f9-7e63-92ba-141813745b02', 'Get product'                         , 'Retrieve a product by its unique identifier within a project.'                                                                                                                                                                                                                                                                          , 'GET'   , '/projects/{project_id}/products/{product_id}', TRUE    ),
('01982303-f0f9-7e63-92ba-141813745b03', 'Update product'                      , 'Update a product''s name or description. Both fields are optional; at least one is required.'                                                                                                                                                                                                                                           , 'PUT'   , '/projects/{project_id}/products/{product_id}', TRUE    ),
('01a01117-dba9-763d-8f4e-968072dbdb52', 'Get project resource limits'         , 'Retrieve the limits that apply to a project and how much of each has been consumed. Read-only: limits are not editable through the API.'                                                                                                                                                                                                , 'GET'   , '/projects/{project_id}/resources_limits'     , TRUE    ),
('01986f44-3a65-7a19-a92d-e6100dd80807', 'Unlink users from project'           , 'Remove user associations from project.'                                                                                                                                                                                                                                                                                                 , 'DELETE', '/projects/{project_id}/users'                , TRUE    ),
('01987096-b4a1-7e8a-8a38-98148daa27a2', 'List users by project'               , 'Retrieve paginated list of users assigned to specific project.'                                                                                                                                                                                                                                                                         , 'GET'   , '/projects/{project_id}/users'                , TRUE    ),
('01986f44-3a65-7a21-9c2b-392f2b0eacf7', 'Link users to project'               , 'Associate multiple users with project.'                                                                                                                                                                                                                                                                                                 , 'POST'  , '/projects/{project_id}/users'                , TRUE    ),
('01a03a46-16d4-7831-9c94-a7975a9c4334', 'List rate limits'                    , 'List the rate-limit rules, with filtering, sorting, partial fields and pagination'                                                                                                                                                                                                                                                      , 'GET'   , '/rate_limits'                                , TRUE    ),
('01a03a46-16d4-7ad9-b646-0bc67824b38c', 'Create rate limit'                   , 'Create a rate-limit rule. The target is validated against the endpoint catalogue, so a rule for a route this service does not serve is refused rather than silently protecting nothing'                                                                                                                                                 , 'POST'  , '/rate_limits'                                , TRUE    ),
('01a03a46-16d4-7b2b-8932-ef9694d8f940', 'Effective rate limits'               , 'Resolve which rules apply to a method and endpoint, one per scope, most specific first. Resolved with the same function the limiter uses, so it cannot disagree with what is enforced'                                                                                                                                                  , 'GET'   , '/rate_limits/effective'                      , TRUE    ),
('01a03a46-16d4-7b1a-913f-e9e50f9acfa7', 'Delete rate limit'                   , 'Delete a rate-limit rule. Its windows are removed with it'                                                                                                                                                                                                                                                                              , 'DELETE', '/rate_limits/{rate_limit_id}'                , TRUE    ),
('01a03a46-16d4-7af9-9f96-d9dc094afd80', 'Get rate limit'                      , 'Retrieve a rate-limit rule and its windows by unique identifier'                                                                                                                                                                                                                                                                        , 'GET'   , '/rate_limits/{rate_limit_id}'                , TRUE    ),
('01a03a46-16d4-7b0a-af95-6805d68a37d3', 'Update rate limit'                   , 'Replace a rate-limit rule. The window set is replaced in full, not merged'                                                                                                                                                                                                                                                              , 'PUT'   , '/rate_limits/{rate_limit_id}'                , TRUE    ),
('01982303-f0f9-7ee0-aa66-0f756c3c8bec', 'List resources'                      , 'Retrieve a paginated list of all available system resources.'                                                                                                                                                                                                                                                                           , 'GET'   , '/resources'                                  , TRUE    ),
('01982303-f0f9-7e44-aeb1-63934913e601', 'Find resources by action and pattern', 'Retrieve a paginated list of resources that match the specified action and resource policy patterns.'                                                                                                                                                                                                                                   , 'GET'   , '/resources/matches'                          , TRUE    ),
('019822c9-9775-71b1-a2c6-deac83cf2519', 'Get resource'                        , 'Retrieve detailed information about a specific system resource configuration using its unique identifier.'                                                                                                                                                                                                                              , 'GET'   , '/resources/{resource_id}'                    , TRUE    ),
('01994754-5db8-7904-80f3-91417f2a4003', 'List resource limits'                , 'Retrieve a paginated list of resource limits in the system with optional filtering, sorting, and field selection'                                                                                                                                                                                                                       , 'GET'   , '/resources_limits'                           , TRUE    ),
('01982303-f0fa-703a-92fa-be272044b2e3', 'List roles'                          , 'Retrieve paginated list of roles with filtering and sorting'                                                                                                                                                                                                                                                                            , 'GET'   , '/roles'                                      , TRUE    ),
('01982303-f0f9-7eff-825d-622a05ef4435', 'Create role'                         , 'Create new role with specified permissions and access levels'                                                                                                                                                                                                                                                                           , 'POST'  , '/roles'                                      , TRUE    ),
('01982303-f0fa-7007-aaf6-462c0b8702ec', 'Delete role'                         , 'Permanently remove role and all associations'                                                                                                                                                                                                                                                                                           , 'DELETE', '/roles/{role_id}'                            , TRUE    ),
('01982303-f0f9-7dde-ab91-1ab138a8b6c5', 'Get role'                            , 'Retrieve role configuration by unique identifier'                                                                                                                                                                                                                                                                                       , 'GET'   , '/roles/{role_id}'                            , TRUE    ),
('01982303-f0f9-7e92-bd69-076fc1cd4a6e', 'Update role'                         , 'Update existing role configuration by identifier'                                                                                                                                                                                                                                                                                       , 'PUT'   , '/roles/{role_id}'                            , TRUE    ),
('01982303-f0f9-7efb-a786-89d7d9db40ee', 'Unlink policies from role'           , 'Remove policy associations from role'                                                                                                                                                                                                                                                                                                   , 'DELETE', '/roles/{role_id}/policies'                   , TRUE    ),
('01982303-f0fa-7036-9474-482fc8e5843d', 'List policies by role'               , 'Retrieve a paginated list of policies associated with a specific role'                                                                                                                                                                                                                                                                  , 'GET'   , '/roles/{role_id}/policies'                   , TRUE    ),
('01982303-f0f9-7edc-bbff-c8fc5dcba075', 'Link policies to role'               , 'Associate multiple policies with role for authorization'                                                                                                                                                                                                                                                                                , 'POST'  , '/roles/{role_id}/policies'                   , TRUE    ),
('01982303-f0f9-7e02-8bf7-c240927de056', 'Unlink users from role'              , 'Remove user associations from role'                                                                                                                                                                                                                                                                                                     , 'DELETE', '/roles/{role_id}/users'                      , TRUE    ),
('01982303-f0fa-7027-9b77-197b693d0e5a', 'List users by role'                  , 'Retrieve paginated list of users assigned to specific role.'                                                                                                                                                                                                                                                                            , 'GET'   , '/roles/{role_id}/users'                      , TRUE    ),
('01982303-f0f9-7e2c-a026-5aec9fbbe375', 'Link users to role'                  , 'Associate multiple users with role for authorization'                                                                                                                                                                                                                                                                                   , 'POST'  , '/roles/{role_id}/users'                      , TRUE    ),
('01982303-f0f9-7daf-809b-4f7880ca9e40', 'List users'                          , 'Retrieve paginated list of users with optional filtering and sorting.'                                                                                                                                                                                                                                                                  , 'GET'   , '/users'                                      , TRUE    ),
('01982303-f0f9-7e78-bddf-389144c4beaf', 'Create user'                         , 'Create a new user account with specified details.'                                                                                                                                                                                                                                                                                      , 'POST'  , '/users'                                      , TRUE    ),
('01982303-f0f9-7dda-84da-cedd68bca775', 'Delete user'                         , 'Permanently remove user account by ID.'                                                                                                                                                                                                                                                                                                 , 'DELETE', '/users/{user_id}'                            , TRUE    ),
('01982303-f0f9-7e25-85f4-4d9d47622702', 'Get user'                            , 'Retrieve user account by unique identifier.'                                                                                                                                                                                                                                                                                            , 'GET'   , '/users/{user_id}'                            , TRUE    ),
('01982303-f0f9-7e3c-a186-f186a3418768', 'Update user'                         , 'Update existing user account details by ID.'                                                                                                                                                                                                                                                                                            , 'PUT'   , '/users/{user_id}'                            , TRUE    ),
('01982303-f0fa-7089-9875-cd42f8e1a3d6', 'Get user authorization'              , 'Retrieve user authorization permissions and roles for access control decisions.'                                                                                                                                                                                                                                                        , 'GET'   , '/users/{user_id}/authz'                      , TRUE    ),
('01986f44-3a65-7a25-afe8-fdd6ae4572c4', 'Unlink projects from user'           , 'Remove project associations from user.'                                                                                                                                                                                                                                                                                                 , 'DELETE', '/users/{user_id}/projects'                   , TRUE    ),
('019870ff-37f6-737e-8efb-e39730ef6952', 'List projects by user'               , 'Retrieve paginated list of projects accessible to specific user.'                                                                                                                                                                                                                                                                       , 'GET'   , '/users/{user_id}/projects'                   , TRUE    ),
('01986f44-3a65-7a2d-8c68-8c579be0aae7', 'Link projects to user'               , 'Associate multiple projects with user.'                                                                                                                                                                                                                                                                                                 , 'POST'  , '/users/{user_id}/projects'                   , TRUE    ),
('01982303-f0f9-7f23-b203-7079222718d0', 'Unlink roles from user'              , 'Remove role associations from user within project.'                                                                                                                                                                                                                                                                                     , 'DELETE', '/users/{user_id}/roles'                      , TRUE    ),
('01982303-f0f9-7e6b-9d17-9b9076785bd6', 'List roles by user'                  , 'Retrieve paginated list of roles assigned to user'                                                                                                                                                                                                                                                                                      , 'GET'   , '/users/{user_id}/roles'                      , TRUE    ),
('01982303-f0fa-700f-a042-0a487ed3c9fb', 'Link roles to user'                  , 'Associate multiple roles with user within project.'                                                                                                                                                                                                                                                                                     , 'POST'  , '/users/{user_id}/roles'                      , TRUE    );

-----------------------------------------------------------------------------------------
-- table policies
-----------------------------------------------------------------------------------------
INSERT INTO policies (id, resources_id, name, description, allowed_action, allowed_resource, system) VALUES
-- full access
('019822c9-9775-7678-b6ea-5c4701531a00', '019822af-b448-7520-a13a-edad1b3f4b93', 'Full Access', 'Allow all actions on all resources', '*', '*', TRUE),
-- Allow logout
('019822c9-9775-7651-9b59-1793ff3b8803', '019822af-b448-7562-a27f-0d02884f3477', 'Allow logout', 'Allow make logout', 'DELETE', '/auth/logout', TRUE),
-- Allow refresh token
('019822c9-9775-73d4-bd51-67ccc8a3964b', '019822af-b448-756a-92b2-791a0e748162', 'Allow refresh token', 'Allow refresh token', 'POST', '/auth/refresh', TRUE),
-- Allow me
('01986fee-b58f-703a-92d3-f1f64ea48710', '0199489b-f2f0-719e-b860-3b7ea6a86a1a', 'Allow me Authorization', 'Allow get authorization information', 'GET', '/me/authz', TRUE),
('0199489b-f2f0-717a-8ee4-5814d4fa1c61', '0199489b-f2f0-718a-a0cb-de8752ea864f', 'Allow me Information', 'Allow get user information', 'GET', '/me', TRUE),
('0199489b-f2f0-718e-a94d-b05a296eb818', '0199489b-f2f0-718e-a94d-b05a296eb818', 'Allow update my information', 'Allow update my information', 'PUT', '/me', TRUE),
-- Allow reset password
('01991b30-2c97-7d5d-a426-7bb7f7c84775', '01991917-2720-758d-8104-94a0368acecb', 'Allow reset password', 'Allow reset password', 'POST', '/auth/password/reset', TRUE),
-- Allow list users
('019ab091-fb85-7b0c-bfec-673266ed8bd0', '01982303-f0f9-7daf-809b-4f7880ca9e40', 'Allow list users', 'Allow list users', 'GET', '/users', TRUE),
-- Seeing your own limits is granted to every authenticated user, exactly as GET /me and
-- GET /me/authz already are: a user who cannot find out why a creation was refused has to guess.
-- The project endpoint (/projects/{project_id}/resources_limits) deliberately gets no blanket
-- grant — project access is granted per user through roles and policies at runtime, the same as
-- every other /projects/{project_id}/... route.
('01a01119-62f4-7a96-9d4a-41c2f56e4086', '01a01117-dba9-74da-bd70-d1acc3842ffa', 'Allow me Resource Limits', 'Allow reading my own resource limits and usage', 'GET', '/me/resources_limits', TRUE),
-- Linking an identity provider to one's own account, and seeing / removing the links. Every
-- signed-in user may do this: the session proves the account, the provider proves the identity.
('01a07576-4ce5-74fd-9e86-ad854feecf73', '01a07319-1d32-7bd2-8ba0-f7da9aaaed0a', 'Allow me Link Identity', 'Allow linking an identity provider to my own account', 'GET', '/auth/idp/*/link', TRUE),
('01a07576-4ce5-75b2-ac8e-0c24302f69c5', '01a07319-1d32-7ca7-834a-d8dcc6a19fa0', 'Allow me Identities', 'Allow listing the identity providers linked to my account', 'GET', '/me/identities', TRUE),
('01a07576-4ce5-75b6-a9b0-efaaf510c9ee', '01a07319-1d32-7cac-885b-6c544f5dbe08', 'Allow me Unlink Identity', 'Allow removing an identity provider from my account', 'DELETE', '/me/identities/*', TRUE);

-----------------------------------------------------------------------------------------
-- table roles_policies
-----------------------------------------------------------------------------------------
INSERT INTO roles_policies (roles_id, policies_id) VALUES
-- Owner
('019822af-b448-750c-ae0d-edaf3aaafc41', '019822c9-9775-7678-b6ea-5c4701531a00'),
-- AuthenticatedUser
('019822af-b448-7514-a670-f7acef5d6f77', '019822c9-9775-7651-9b59-1793ff3b8803'),
('019822af-b448-7514-a670-f7acef5d6f77', '019822c9-9775-73d4-bd51-67ccc8a3964b'),
('019822af-b448-7514-a670-f7acef5d6f77', '01986fee-b58f-703a-92d3-f1f64ea48710'),
('019822af-b448-7514-a670-f7acef5d6f77', '01991b30-2c97-7d5d-a426-7bb7f7c84775'),
('019822af-b448-7514-a670-f7acef5d6f77', '019ab091-fb85-7b0c-bfec-673266ed8bd0'),
('019822af-b448-7514-a670-f7acef5d6f77', '01a01119-62f4-7a96-9d4a-41c2f56e4086'),
('019822af-b448-7514-a670-f7acef5d6f77', '01a07576-4ce5-74fd-9e86-ad854feecf73'),
('019822af-b448-7514-a670-f7acef5d6f77', '01a07576-4ce5-75b2-ac8e-0c24302f69c5'),
('019822af-b448-7514-a670-f7acef5d6f77', '01a07576-4ce5-75b6-a9b0-efaaf510c9ee');

-----------------------------------------------------------------------------------------
-- table users_roles
-----------------------------------------------------------------------------------------
INSERT INTO users_roles (users_id, roles_id) VALUES
-- Administrator
('019822af-b448-73fb-89a1-447e8f8d1cde', '019822af-b448-750c-ae0d-edaf3aaafc41');

-- +goose StatementEnd
--

-- +goose Down
-- +goose StatementBegin

-- Link tables first, then the rows they reference. Every seeded row is system = TRUE, and
-- fn_restrict_delete_update_on_system rejects DELETE as well as
-- UPDATE — so the flag cannot be cleared first and the triggers have to be disabled.
--
DELETE FROM users_roles;
DELETE FROM roles_policies;

ALTER TABLE policies DISABLE TRIGGER tr_restrict_delete_update_on_system_policies;
DELETE FROM policies;
ALTER TABLE policies ENABLE TRIGGER tr_restrict_delete_update_on_system_policies;

ALTER TABLE resources DISABLE TRIGGER tr_restrict_delete_update_on_system_resources;
DELETE FROM resources;
ALTER TABLE resources ENABLE TRIGGER tr_restrict_delete_update_on_system_resources;

ALTER TABLE roles DISABLE TRIGGER tr_restrict_delete_update_on_system_roles;
DELETE FROM roles;
ALTER TABLE roles ENABLE TRIGGER tr_restrict_delete_update_on_system_roles;

-- +goose StatementEnd
