// Code generated by MockGen. DO NOT EDIT.
// Source: health.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../mocks/service/health_app.go -source=health.go AppHealthProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAppHealthProvider is a mock of AppHealthProvider interface.
type MockAppHealthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAppHealthProviderMockRecorder
	isgomock struct{}
}

// MockAppHealthProviderMockRecorder is the mock recorder for MockAppHealthProvider.
type MockAppHealthProviderMockRecorder struct {
	mock *MockAppHealthProvider
}

// NewMockAppHealthProvider creates a new mock instance.
func NewMockAppHealthProvider(ctrl *gomock.Controller) *MockAppHealthProvider {
	mock := &MockAppHealthProvider{ctrl: ctrl}
	mock.recorder = &MockAppHealthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppHealthProvider) EXPECT() *MockAppHealthProviderMockRecorder {
	return m.recorder
}

// GetHealth mocks base method.
func (m *MockAppHealthProvider) GetHealth(ctx context.Context) domain.DetailedHealth {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHealth", ctx)
	ret0, _ := ret[0].(domain.DetailedHealth)
	return ret0
}

// GetHealth indicates an expected call of GetHealth.
func (mr *MockAppHealthProviderMockRecorder) GetHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHealth", reflect.TypeOf((*MockAppHealthProvider)(nil).GetHealth), ctx)
}
