// Code generated by MockGen. DO NOT EDIT.
// Source: idp_types.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/idp_types.go -source=idp_types.go IDPTypes
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIDPTypes is a mock of IDPTypes interface.
type MockIDPTypes struct {
	ctrl     *gomock.Controller
	recorder *MockIDPTypesMockRecorder
	isgomock struct{}
}

// MockIDPTypesMockRecorder is the mock recorder for MockIDPTypes.
type MockIDPTypesMockRecorder struct {
	mock *MockIDPTypes
}

// NewMockIDPTypes creates a new mock instance.
func NewMockIDPTypes(ctrl *gomock.Controller) *MockIDPTypes {
	mock := &MockIDPTypes{ctrl: ctrl}
	mock.recorder = &MockIDPTypesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDPTypes) EXPECT() *MockIDPTypesMockRecorder {
	return m.recorder
}

// Select mocks base method.
func (m *MockIDPTypes) Select(ctx context.Context, input *domain.SelectIDPTypesInput) (*domain.ListIDPTypesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, input)
	ret0, _ := ret[0].(*domain.ListIDPTypesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockIDPTypesMockRecorder) Select(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockIDPTypes)(nil).Select), ctx, input)
}

// SelectByID mocks base method.
func (m *MockIDPTypes) SelectByID(ctx context.Context, id uuid.UUID) (*domain.IDPTypes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByID", ctx, id)
	ret0, _ := ret[0].(*domain.IDPTypes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByID indicates an expected call of SelectByID.
func (mr *MockIDPTypesMockRecorder) SelectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByID", reflect.TypeOf((*MockIDPTypes)(nil).SelectByID), ctx, id)
}

// SelectByName mocks base method.
func (m *MockIDPTypes) SelectByName(ctx context.Context, name string) (*domain.IDPTypes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByName", ctx, name)
	ret0, _ := ret[0].(*domain.IDPTypes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByName indicates an expected call of SelectByName.
func (mr *MockIDPTypesMockRecorder) SelectByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByName", reflect.TypeOf((*MockIDPTypes)(nil).SelectByName), ctx, name)
}
