// Code generated by MockGen. DO NOT EDIT.
// Source: idps.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/idps.go -source=idps.go IDPs
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIDPs is a mock of IDPs interface.
type MockIDPs struct {
	ctrl     *gomock.Controller
	recorder *MockIDPsMockRecorder
	isgomock struct{}
}

// MockIDPsMockRecorder is the mock recorder for MockIDPs.
type MockIDPsMockRecorder struct {
	mock *MockIDPs
}

// NewMockIDPs creates a new mock instance.
func NewMockIDPs(ctrl *gomock.Controller) *MockIDPs {
	mock := &MockIDPs{ctrl: ctrl}
	mock.recorder = &MockIDPsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDPs) EXPECT() *MockIDPsMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockIDPs) DeleteByID(ctx context.Context, input *domain.DeleteIDPInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIDPsMockRecorder) DeleteByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIDPs)(nil).DeleteByID), ctx, input)
}

// Insert mocks base method.
func (m *MockIDPs) Insert(ctx context.Context, input *domain.InsertIDPInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockIDPsMockRecorder) Insert(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIDPs)(nil).Insert), ctx, input)
}

// Select mocks base method.
func (m *MockIDPs) Select(ctx context.Context, input *domain.SelectIDPsInput) (*domain.ListIDPsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, input)
	ret0, _ := ret[0].(*domain.ListIDPsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockIDPsMockRecorder) Select(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockIDPs)(nil).Select), ctx, input)
}

// SelectByID mocks base method.
func (m *MockIDPs) SelectByID(ctx context.Context, id uuid.UUID) (*domain.IDP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByID", ctx, id)
	ret0, _ := ret[0].(*domain.IDP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByID indicates an expected call of SelectByID.
func (mr *MockIDPsMockRecorder) SelectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByID", reflect.TypeOf((*MockIDPs)(nil).SelectByID), ctx, id)
}

// SelectByName mocks base method.
func (m *MockIDPs) SelectByName(ctx context.Context, name string) (*domain.IDP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByName", ctx, name)
	ret0, _ := ret[0].(*domain.IDP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByName indicates an expected call of SelectByName.
func (mr *MockIDPsMockRecorder) SelectByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByName", reflect.TypeOf((*MockIDPs)(nil).SelectByName), ctx, name)
}

// UpdateByID mocks base method.
func (m *MockIDPs) UpdateByID(ctx context.Context, input *domain.UpdateIDPInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockIDPsMockRecorder) UpdateByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockIDPs)(nil).UpdateByID), ctx, input)
}
