// Code generated by MockGen. DO NOT EDIT.
// Source: notifier.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/notifier.go -source=notifier.go Notifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	notifier "github.com/slashdevops/go-rest-api-service-template/internal/core/port/driven/notifier"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// SendAccountExists mocks base method.
func (m *MockNotifier) SendAccountExists(ctx context.Context, to notifier.Recipient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAccountExists", ctx, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAccountExists indicates an expected call of SendAccountExists.
func (mr *MockNotifierMockRecorder) SendAccountExists(ctx, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAccountExists", reflect.TypeOf((*MockNotifier)(nil).SendAccountExists), ctx, to)
}

// SendAccountVerification mocks base method.
func (m *MockNotifier) SendAccountVerification(ctx context.Context, to notifier.Recipient, token, ttlHuman string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAccountVerification", ctx, to, token, ttlHuman)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAccountVerification indicates an expected call of SendAccountVerification.
func (mr *MockNotifierMockRecorder) SendAccountVerification(ctx, to, token, ttlHuman any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAccountVerification", reflect.TypeOf((*MockNotifier)(nil).SendAccountVerification), ctx, to, token, ttlHuman)
}

// SendPasswordReset mocks base method.
func (m *MockNotifier) SendPasswordReset(ctx context.Context, to notifier.Recipient, token, ttlHuman string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordReset", ctx, to, token, ttlHuman)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordReset indicates an expected call of SendPasswordReset.
func (mr *MockNotifierMockRecorder) SendPasswordReset(ctx, to, token, ttlHuman any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordReset", reflect.TypeOf((*MockNotifier)(nil).SendPasswordReset), ctx, to, token, ttlHuman)
}
