// Code generated by MockGen. DO NOT EDIT.
// Source: policies.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/policies.go -source=policies.go Policies
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicies is a mock of Policies interface.
type MockPolicies struct {
	ctrl     *gomock.Controller
	recorder *MockPoliciesMockRecorder
	isgomock struct{}
}

// MockPoliciesMockRecorder is the mock recorder for MockPolicies.
type MockPoliciesMockRecorder struct {
	mock *MockPolicies
}

// NewMockPolicies creates a new mock instance.
func NewMockPolicies(ctrl *gomock.Controller) *MockPolicies {
	mock := &MockPolicies{ctrl: ctrl}
	mock.recorder = &MockPoliciesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicies) EXPECT() *MockPoliciesMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockPolicies) DeleteByID(ctx context.Context, input *domain.DeletePolicyInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockPoliciesMockRecorder) DeleteByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockPolicies)(nil).DeleteByID), ctx, input)
}

// Insert mocks base method.
func (m *MockPolicies) Insert(ctx context.Context, input *domain.CreatePolicyInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockPoliciesMockRecorder) Insert(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockPolicies)(nil).Insert), ctx, input)
}

// LinkRoles mocks base method.
func (m *MockPolicies) LinkRoles(ctx context.Context, input *domain.LinkRolesToPolicyInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkRoles", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkRoles indicates an expected call of LinkRoles.
func (mr *MockPoliciesMockRecorder) LinkRoles(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkRoles", reflect.TypeOf((*MockPolicies)(nil).LinkRoles), ctx, input)
}

// Select mocks base method.
func (m *MockPolicies) Select(ctx context.Context, input *domain.SelectPoliciesInput) (*domain.SelectPoliciesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, input)
	ret0, _ := ret[0].(*domain.SelectPoliciesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockPoliciesMockRecorder) Select(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockPolicies)(nil).Select), ctx, input)
}

// SelectByID mocks base method.
func (m *MockPolicies) SelectByID(ctx context.Context, id uuid.UUID) (*domain.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByID", ctx, id)
	ret0, _ := ret[0].(*domain.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByID indicates an expected call of SelectByID.
func (mr *MockPoliciesMockRecorder) SelectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByID", reflect.TypeOf((*MockPolicies)(nil).SelectByID), ctx, id)
}

// SelectByRoleID mocks base method.
func (m *MockPolicies) SelectByRoleID(ctx context.Context, roleID uuid.UUID, input *domain.SelectPoliciesInput) (*domain.SelectPoliciesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByRoleID", ctx, roleID, input)
	ret0, _ := ret[0].(*domain.SelectPoliciesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByRoleID indicates an expected call of SelectByRoleID.
func (mr *MockPoliciesMockRecorder) SelectByRoleID(ctx, roleID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByRoleID", reflect.TypeOf((*MockPolicies)(nil).SelectByRoleID), ctx, roleID, input)
}

// UnlinkRoles mocks base method.
func (m *MockPolicies) UnlinkRoles(ctx context.Context, input *domain.UnlinkRolesFromPolicyInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkRoles", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkRoles indicates an expected call of UnlinkRoles.
func (mr *MockPoliciesMockRecorder) UnlinkRoles(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkRoles", reflect.TypeOf((*MockPolicies)(nil).UnlinkRoles), ctx, input)
}

// UpdateByID mocks base method.
func (m *MockPolicies) UpdateByID(ctx context.Context, input *domain.UpdatePolicyInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockPoliciesMockRecorder) UpdateByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockPolicies)(nil).UpdateByID), ctx, input)
}
