// Code generated by MockGen. DO NOT EDIT.
// Source: products.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/products.go -source=products.go Products
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockProducts is a mock of Products interface.
type MockProducts struct {
	ctrl     *gomock.Controller
	recorder *MockProductsMockRecorder
	isgomock struct{}
}

// MockProductsMockRecorder is the mock recorder for MockProducts.
type MockProductsMockRecorder struct {
	mock *MockProducts
}

// NewMockProducts creates a new mock instance.
func NewMockProducts(ctrl *gomock.Controller) *MockProducts {
	mock := &MockProducts{ctrl: ctrl}
	mock.recorder = &MockProductsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducts) EXPECT() *MockProductsMockRecorder {
	return m.recorder
}

// DeleteByIDByProjectID mocks base method.
func (m *MockProducts) DeleteByIDByProjectID(ctx context.Context, input *domain.DeleteProductInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIDByProjectID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByIDByProjectID indicates an expected call of DeleteByIDByProjectID.
func (mr *MockProductsMockRecorder) DeleteByIDByProjectID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIDByProjectID", reflect.TypeOf((*MockProducts)(nil).DeleteByIDByProjectID), ctx, input)
}

// InsertByProjectID mocks base method.
func (m *MockProducts) InsertByProjectID(ctx context.Context, input *domain.InsertProductInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertByProjectID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertByProjectID indicates an expected call of InsertByProjectID.
func (mr *MockProductsMockRecorder) InsertByProjectID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertByProjectID", reflect.TypeOf((*MockProducts)(nil).InsertByProjectID), ctx, input)
}

// Select mocks base method.
func (m *MockProducts) Select(ctx context.Context, input *domain.SelectProductsInput) (*domain.SelectProductsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, input)
	ret0, _ := ret[0].(*domain.SelectProductsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockProductsMockRecorder) Select(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockProducts)(nil).Select), ctx, input)
}

// SelectByIDByProjectID mocks base method.
func (m *MockProducts) SelectByIDByProjectID(ctx context.Context, id, projectID, userID uuid.UUID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByIDByProjectID", ctx, id, projectID, userID)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByIDByProjectID indicates an expected call of SelectByIDByProjectID.
func (mr *MockProductsMockRecorder) SelectByIDByProjectID(ctx, id, projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByIDByProjectID", reflect.TypeOf((*MockProducts)(nil).SelectByIDByProjectID), ctx, id, projectID, userID)
}

// SelectByProjectID mocks base method.
func (m *MockProducts) SelectByProjectID(ctx context.Context, projectID, userID uuid.UUID, input *domain.SelectProductsInput) (*domain.SelectProductsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByProjectID", ctx, projectID, userID, input)
	ret0, _ := ret[0].(*domain.SelectProductsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByProjectID indicates an expected call of SelectByProjectID.
func (mr *MockProductsMockRecorder) SelectByProjectID(ctx, projectID, userID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByProjectID", reflect.TypeOf((*MockProducts)(nil).SelectByProjectID), ctx, projectID, userID, input)
}

// UpdateByIDByProjectID mocks base method.
func (m *MockProducts) UpdateByIDByProjectID(ctx context.Context, input *domain.UpdateProductInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByIDByProjectID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByIDByProjectID indicates an expected call of UpdateByIDByProjectID.
func (mr *MockProductsMockRecorder) UpdateByIDByProjectID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByIDByProjectID", reflect.TypeOf((*MockProducts)(nil).UpdateByIDByProjectID), ctx, input)
}
