// Code generated by MockGen. DO NOT EDIT.
// Source: projects.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/projects.go -source=projects.go Projects
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockProjects is a mock of Projects interface.
type MockProjects struct {
	ctrl     *gomock.Controller
	recorder *MockProjectsMockRecorder
	isgomock struct{}
}

// MockProjectsMockRecorder is the mock recorder for MockProjects.
type MockProjectsMockRecorder struct {
	mock *MockProjects
}

// NewMockProjects creates a new mock instance.
func NewMockProjects(ctrl *gomock.Controller) *MockProjects {
	mock := &MockProjects{ctrl: ctrl}
	mock.recorder = &MockProjectsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjects) EXPECT() *MockProjectsMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockProjects) DeleteByID(ctx context.Context, input *domain.DeleteProjectInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockProjectsMockRecorder) DeleteByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockProjects)(nil).DeleteByID), ctx, input)
}

// Insert mocks base method.
func (m *MockProjects) Insert(ctx context.Context, input *domain.InsertProjectInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockProjectsMockRecorder) Insert(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockProjects)(nil).Insert), ctx, input)
}

// LinkUsers mocks base method.
func (m *MockProjects) LinkUsers(ctx context.Context, input *domain.LinkUsersToProjectInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkUsers", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkUsers indicates an expected call of LinkUsers.
func (mr *MockProjectsMockRecorder) LinkUsers(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkUsers", reflect.TypeOf((*MockProjects)(nil).LinkUsers), ctx, input)
}

// Select mocks base method.
func (m *MockProjects) Select(ctx context.Context, input *domain.SelectProjectsInput) (*domain.SelectProjectsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, input)
	ret0, _ := ret[0].(*domain.SelectProjectsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockProjectsMockRecorder) Select(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockProjects)(nil).Select), ctx, input)
}

// SelectByIDByUserID mocks base method.
func (m *MockProjects) SelectByIDByUserID(ctx context.Context, id, userID uuid.UUID) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByIDByUserID", ctx, id, userID)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByIDByUserID indicates an expected call of SelectByIDByUserID.
func (mr *MockProjectsMockRecorder) SelectByIDByUserID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByIDByUserID", reflect.TypeOf((*MockProjects)(nil).SelectByIDByUserID), ctx, id, userID)
}

// SelectByUserID mocks base method.
func (m *MockProjects) SelectByUserID(ctx context.Context, input *domain.SelectProjectsInput) (*domain.SelectProjectsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByUserID", ctx, input)
	ret0, _ := ret[0].(*domain.SelectProjectsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByUserID indicates an expected call of SelectByUserID.
func (mr *MockProjectsMockRecorder) SelectByUserID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByUserID", reflect.TypeOf((*MockProjects)(nil).SelectByUserID), ctx, input)
}

// UnlinkUsers mocks base method.
func (m *MockProjects) UnlinkUsers(ctx context.Context, input *domain.UnlinkUsersFromProjectInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkUsers", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkUsers indicates an expected call of UnlinkUsers.
func (mr *MockProjectsMockRecorder) UnlinkUsers(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkUsers", reflect.TypeOf((*MockProjects)(nil).UnlinkUsers), ctx, input)
}

// UpdateByID mocks base method.
func (m *MockProjects) UpdateByID(ctx context.Context, input *domain.UpdateProjectInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockProjectsMockRecorder) UpdateByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockProjects)(nil).UpdateByID), ctx, input)
}
