// Code generated by MockGen. DO NOT EDIT.
// Source: rate_limits.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/rate_limits.go -source=rate_limits.go RateLimits
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRateLimits is a mock of RateLimits interface.
type MockRateLimits struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimitsMockRecorder
	isgomock struct{}
}

// MockRateLimitsMockRecorder is the mock recorder for MockRateLimits.
type MockRateLimitsMockRecorder struct {
	mock *MockRateLimits
}

// NewMockRateLimits creates a new mock instance.
func NewMockRateLimits(ctrl *gomock.Controller) *MockRateLimits {
	mock := &MockRateLimits{ctrl: ctrl}
	mock.recorder = &MockRateLimitsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimits) EXPECT() *MockRateLimitsMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockRateLimits) DeleteByID(ctx context.Context, input *domain.DeleteRateLimitInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockRateLimitsMockRecorder) DeleteByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockRateLimits)(nil).DeleteByID), ctx, input)
}

// Insert mocks base method.
func (m *MockRateLimits) Insert(ctx context.Context, input *domain.CreateRateLimitInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockRateLimitsMockRecorder) Insert(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRateLimits)(nil).Insert), ctx, input)
}

// Select mocks base method.
func (m *MockRateLimits) Select(ctx context.Context, input *domain.SelectRateLimitsInput) (*domain.SelectRateLimitsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, input)
	ret0, _ := ret[0].(*domain.SelectRateLimitsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockRateLimitsMockRecorder) Select(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockRateLimits)(nil).Select), ctx, input)
}

// SelectAll mocks base method.
func (m *MockRateLimits) SelectAll(ctx context.Context) ([]domain.RateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAll", ctx)
	ret0, _ := ret[0].([]domain.RateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAll indicates an expected call of SelectAll.
func (mr *MockRateLimitsMockRecorder) SelectAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAll", reflect.TypeOf((*MockRateLimits)(nil).SelectAll), ctx)
}

// SelectByID mocks base method.
func (m *MockRateLimits) SelectByID(ctx context.Context, id uuid.UUID) (*domain.RateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByID", ctx, id)
	ret0, _ := ret[0].(*domain.RateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByID indicates an expected call of SelectByID.
func (mr *MockRateLimitsMockRecorder) SelectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByID", reflect.TypeOf((*MockRateLimits)(nil).SelectByID), ctx, id)
}

// UpdateByID mocks base method.
func (m *MockRateLimits) UpdateByID(ctx context.Context, input *domain.UpdateRateLimitInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockRateLimitsMockRecorder) UpdateByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockRateLimits)(nil).UpdateByID), ctx, input)
}
