// Code generated by MockGen. DO NOT EDIT.
// Source: resources_limits.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/resources_limits.go -source=resources_limits.go ResourcesLimits
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	repository "github.com/slashdevops/go-rest-api-service-template/internal/core/port/driven/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockResourcesLimits is a mock of ResourcesLimits interface.
type MockResourcesLimits struct {
	ctrl     *gomock.Controller
	recorder *MockResourcesLimitsMockRecorder
	isgomock struct{}
}

// MockResourcesLimitsMockRecorder is the mock recorder for MockResourcesLimits.
type MockResourcesLimitsMockRecorder struct {
	mock *MockResourcesLimits
}

// NewMockResourcesLimits creates a new mock instance.
func NewMockResourcesLimits(ctrl *gomock.Controller) *MockResourcesLimits {
	mock := &MockResourcesLimits{ctrl: ctrl}
	mock.recorder = &MockResourcesLimitsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourcesLimits) EXPECT() *MockResourcesLimitsMockRecorder {
	return m.recorder
}

// CheckUsage mocks base method.
func (m *MockResourcesLimits) CheckUsage(ctx context.Context, scope domain.ResourcesLimitsScope, resourceType domain.ResourcesLimitsResourceType) (*domain.ResourcesLimitsCheckUsageOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUsage", ctx, scope, resourceType)
	ret0, _ := ret[0].(*domain.ResourcesLimitsCheckUsageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUsage indicates an expected call of CheckUsage.
func (mr *MockResourcesLimitsMockRecorder) CheckUsage(ctx, scope, resourceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUsage", reflect.TypeOf((*MockResourcesLimits)(nil).CheckUsage), ctx, scope, resourceType)
}

// DecrementUsage mocks base method.
func (m *MockResourcesLimits) DecrementUsage(ctx context.Context, scope domain.ResourcesLimitsScope, resourceType domain.ResourcesLimitsResourceType, sign repository.ResourcesLimitsSigner) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementUsage", ctx, scope, resourceType, sign)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementUsage indicates an expected call of DecrementUsage.
func (mr *MockResourcesLimitsMockRecorder) DecrementUsage(ctx, scope, resourceType, sign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementUsage", reflect.TypeOf((*MockResourcesLimits)(nil).DecrementUsage), ctx, scope, resourceType, sign)
}

// IncrementUsage mocks base method.
func (m *MockResourcesLimits) IncrementUsage(ctx context.Context, scope domain.ResourcesLimitsScope, resourceType domain.ResourcesLimitsResourceType, sign repository.ResourcesLimitsSigner) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUsage", ctx, scope, resourceType, sign)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementUsage indicates an expected call of IncrementUsage.
func (mr *MockResourcesLimitsMockRecorder) IncrementUsage(ctx, scope, resourceType, sign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUsage", reflect.TypeOf((*MockResourcesLimits)(nil).IncrementUsage), ctx, scope, resourceType, sign)
}

// RecountUsage mocks base method.
func (m *MockResourcesLimits) RecountUsage(ctx context.Context, scope domain.ResourcesLimitsScope, resourceType domain.ResourcesLimitsResourceType, sign repository.ResourcesLimitsSigner) (*domain.ResourcesLimitsRecountOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecountUsage", ctx, scope, resourceType, sign)
	ret0, _ := ret[0].(*domain.ResourcesLimitsRecountOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecountUsage indicates an expected call of RecountUsage.
func (mr *MockResourcesLimitsMockRecorder) RecountUsage(ctx, scope, resourceType, sign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecountUsage", reflect.TypeOf((*MockResourcesLimits)(nil).RecountUsage), ctx, scope, resourceType, sign)
}

// ReserveUsage mocks base method.
func (m *MockResourcesLimits) ReserveUsage(ctx context.Context, scope domain.ResourcesLimitsScope, resourceType domain.ResourcesLimitsResourceType, verify repository.ResourcesLimitsVerifier, sign repository.ResourcesLimitsSigner) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveUsage", ctx, scope, resourceType, verify, sign)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveUsage indicates an expected call of ReserveUsage.
func (mr *MockResourcesLimitsMockRecorder) ReserveUsage(ctx, scope, resourceType, verify, sign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveUsage", reflect.TypeOf((*MockResourcesLimits)(nil).ReserveUsage), ctx, scope, resourceType, verify, sign)
}

// Select mocks base method.
func (m *MockResourcesLimits) Select(ctx context.Context, input *domain.SelectResourcesLimitsInput) (*domain.SelectResourcesLimitsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, input)
	ret0, _ := ret[0].(*domain.SelectResourcesLimitsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockResourcesLimitsMockRecorder) Select(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockResourcesLimits)(nil).Select), ctx, input)
}

// SelectTrackedScopes mocks base method.
func (m *MockResourcesLimits) SelectTrackedScopes(ctx context.Context) ([]domain.ResourcesLimitsTrackedScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectTrackedScopes", ctx)
	ret0, _ := ret[0].([]domain.ResourcesLimitsTrackedScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectTrackedScopes indicates an expected call of SelectTrackedScopes.
func (mr *MockResourcesLimitsMockRecorder) SelectTrackedScopes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectTrackedScopes", reflect.TypeOf((*MockResourcesLimits)(nil).SelectTrackedScopes), ctx)
}
