// Code generated by MockGen. DO NOT EDIT.
// Source: resources_limits.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../mocks/service/resources_limits_consumer.go -source=resources_limits.go ResourcesLimitsServiceConsumer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockResourcesLimitsServiceConsumer is a mock of ResourcesLimitsServiceConsumer interface.
type MockResourcesLimitsServiceConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockResourcesLimitsServiceConsumerMockRecorder
	isgomock struct{}
}

// MockResourcesLimitsServiceConsumerMockRecorder is the mock recorder for MockResourcesLimitsServiceConsumer.
type MockResourcesLimitsServiceConsumerMockRecorder struct {
	mock *MockResourcesLimitsServiceConsumer
}

// NewMockResourcesLimitsServiceConsumer creates a new mock instance.
func NewMockResourcesLimitsServiceConsumer(ctrl *gomock.Controller) *MockResourcesLimitsServiceConsumer {
	mock := &MockResourcesLimitsServiceConsumer{ctrl: ctrl}
	mock.recorder = &MockResourcesLimitsServiceConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourcesLimitsServiceConsumer) EXPECT() *MockResourcesLimitsServiceConsumerMockRecorder {
	return m.recorder
}

// CheckUsage mocks base method.
func (m *MockResourcesLimitsServiceConsumer) CheckUsage(ctx context.Context, scope domain.ResourcesLimitsScope, resourceType domain.ResourcesLimitsResourceType) (*domain.ResourcesLimitsStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUsage", ctx, scope, resourceType)
	ret0, _ := ret[0].(*domain.ResourcesLimitsStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUsage indicates an expected call of CheckUsage.
func (mr *MockResourcesLimitsServiceConsumerMockRecorder) CheckUsage(ctx, scope, resourceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUsage", reflect.TypeOf((*MockResourcesLimitsServiceConsumer)(nil).CheckUsage), ctx, scope, resourceType)
}

// DecrementUsage mocks base method.
func (m *MockResourcesLimitsServiceConsumer) DecrementUsage(ctx context.Context, scope domain.ResourcesLimitsScope, resourceType domain.ResourcesLimitsResourceType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementUsage", ctx, scope, resourceType)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementUsage indicates an expected call of DecrementUsage.
func (mr *MockResourcesLimitsServiceConsumerMockRecorder) DecrementUsage(ctx, scope, resourceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementUsage", reflect.TypeOf((*MockResourcesLimitsServiceConsumer)(nil).DecrementUsage), ctx, scope, resourceType)
}

// IncrementUsage mocks base method.
func (m *MockResourcesLimitsServiceConsumer) IncrementUsage(ctx context.Context, scope domain.ResourcesLimitsScope, resourceType domain.ResourcesLimitsResourceType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUsage", ctx, scope, resourceType)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementUsage indicates an expected call of IncrementUsage.
func (mr *MockResourcesLimitsServiceConsumerMockRecorder) IncrementUsage(ctx, scope, resourceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUsage", reflect.TypeOf((*MockResourcesLimitsServiceConsumer)(nil).IncrementUsage), ctx, scope, resourceType)
}

// ReserveUsage mocks base method.
func (m *MockResourcesLimitsServiceConsumer) ReserveUsage(ctx context.Context, scope domain.ResourcesLimitsScope, resourceType domain.ResourcesLimitsResourceType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveUsage", ctx, scope, resourceType)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReserveUsage indicates an expected call of ReserveUsage.
func (mr *MockResourcesLimitsServiceConsumerMockRecorder) ReserveUsage(ctx, scope, resourceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveUsage", reflect.TypeOf((*MockResourcesLimitsServiceConsumer)(nil).ReserveUsage), ctx, scope, resourceType)
}
