// Code generated by MockGen. DO NOT EDIT.
// Source: revoked_tokens.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/revoked_tokens.go -source=revoked_tokens.go RevokedTokens
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRevokedTokens is a mock of RevokedTokens interface.
type MockRevokedTokens struct {
	ctrl     *gomock.Controller
	recorder *MockRevokedTokensMockRecorder
	isgomock struct{}
}

// MockRevokedTokensMockRecorder is the mock recorder for MockRevokedTokens.
type MockRevokedTokensMockRecorder struct {
	mock *MockRevokedTokens
}

// NewMockRevokedTokens creates a new mock instance.
func NewMockRevokedTokens(ctrl *gomock.Controller) *MockRevokedTokens {
	mock := &MockRevokedTokens{ctrl: ctrl}
	mock.recorder = &MockRevokedTokensMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRevokedTokens) EXPECT() *MockRevokedTokensMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockRevokedTokens) Consume(ctx context.Context, jti, userID uuid.UUID, expiresAt time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, jti, userID, expiresAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockRevokedTokensMockRecorder) Consume(ctx, jti, userID, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockRevokedTokens)(nil).Consume), ctx, jti, userID, expiresAt)
}

// DeleteExpired mocks base method.
func (m *MockRevokedTokens) DeleteExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockRevokedTokensMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockRevokedTokens)(nil).DeleteExpired), ctx)
}

// Get mocks base method.
func (m *MockRevokedTokens) Get(ctx context.Context, jti uuid.UUID) (*domain.TokenRevocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, jti)
	ret0, _ := ret[0].(*domain.TokenRevocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRevokedTokensMockRecorder) Get(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRevokedTokens)(nil).Get), ctx, jti)
}

// Revoke mocks base method.
func (m *MockRevokedTokens) Revoke(ctx context.Context, jti, userID uuid.UUID, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, jti, userID, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRevokedTokensMockRecorder) Revoke(ctx, jti, userID, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRevokedTokens)(nil).Revoke), ctx, jti, userID, expiresAt)
}

// RevokeChain mocks base method.
func (m *MockRevokedTokens) RevokeChain(ctx context.Context, jti, userID uuid.UUID, expiresAt time.Time) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeChain", ctx, jti, userID, expiresAt)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeChain indicates an expected call of RevokeChain.
func (mr *MockRevokedTokensMockRecorder) RevokeChain(ctx, jti, userID, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeChain", reflect.TypeOf((*MockRevokedTokens)(nil).RevokeChain), ctx, jti, userID, expiresAt)
}

// Rotate mocks base method.
func (m *MockRevokedTokens) Rotate(ctx context.Context, oldJTI, newJTI, userID uuid.UUID, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, oldJTI, newJTI, userID, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rotate indicates an expected call of Rotate.
func (mr *MockRevokedTokensMockRecorder) Rotate(ctx, oldJTI, newJTI, userID, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockRevokedTokens)(nil).Rotate), ctx, oldJTI, newJTI, userID, expiresAt)
}

// SelectUnexpiredJTIs mocks base method.
func (m *MockRevokedTokens) SelectUnexpiredJTIs(ctx context.Context, horizon time.Duration) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUnexpiredJTIs", ctx, horizon)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUnexpiredJTIs indicates an expected call of SelectUnexpiredJTIs.
func (mr *MockRevokedTokensMockRecorder) SelectUnexpiredJTIs(ctx, horizon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUnexpiredJTIs", reflect.TypeOf((*MockRevokedTokens)(nil).SelectUnexpiredJTIs), ctx, horizon)
}
