// Code generated by MockGen. DO NOT EDIT.
// Source: roles.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/roles.go -source=roles.go Roles
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRoles is a mock of Roles interface.
type MockRoles struct {
	ctrl     *gomock.Controller
	recorder *MockRolesMockRecorder
	isgomock struct{}
}

// MockRolesMockRecorder is the mock recorder for MockRoles.
type MockRolesMockRecorder struct {
	mock *MockRoles
}

// NewMockRoles creates a new mock instance.
func NewMockRoles(ctrl *gomock.Controller) *MockRoles {
	mock := &MockRoles{ctrl: ctrl}
	mock.recorder = &MockRolesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoles) EXPECT() *MockRolesMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockRoles) DeleteByID(ctx context.Context, input *domain.DeleteRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockRolesMockRecorder) DeleteByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockRoles)(nil).DeleteByID), ctx, input)
}

// Insert mocks base method.
func (m *MockRoles) Insert(ctx context.Context, input *domain.InsertRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockRolesMockRecorder) Insert(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRoles)(nil).Insert), ctx, input)
}

// LinkPolicies mocks base method.
func (m *MockRoles) LinkPolicies(ctx context.Context, input *domain.LinkPoliciesToRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkPolicies", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkPolicies indicates an expected call of LinkPolicies.
func (mr *MockRolesMockRecorder) LinkPolicies(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkPolicies", reflect.TypeOf((*MockRoles)(nil).LinkPolicies), ctx, input)
}

// LinkUsers mocks base method.
func (m *MockRoles) LinkUsers(ctx context.Context, input *domain.LinkUsersToRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkUsers", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkUsers indicates an expected call of LinkUsers.
func (mr *MockRolesMockRecorder) LinkUsers(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkUsers", reflect.TypeOf((*MockRoles)(nil).LinkUsers), ctx, input)
}

// Select mocks base method.
func (m *MockRoles) Select(ctx context.Context, input *domain.SelectRolesInput) (*domain.SelectRolesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, input)
	ret0, _ := ret[0].(*domain.SelectRolesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockRolesMockRecorder) Select(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockRoles)(nil).Select), ctx, input)
}

// SelectByID mocks base method.
func (m *MockRoles) SelectByID(ctx context.Context, id uuid.UUID) (*domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByID", ctx, id)
	ret0, _ := ret[0].(*domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByID indicates an expected call of SelectByID.
func (mr *MockRolesMockRecorder) SelectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByID", reflect.TypeOf((*MockRoles)(nil).SelectByID), ctx, id)
}

// SelectByPolicyID mocks base method.
func (m *MockRoles) SelectByPolicyID(ctx context.Context, policyID uuid.UUID, input *domain.SelectRolesInput) (*domain.SelectRolesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByPolicyID", ctx, policyID, input)
	ret0, _ := ret[0].(*domain.SelectRolesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByPolicyID indicates an expected call of SelectByPolicyID.
func (mr *MockRolesMockRecorder) SelectByPolicyID(ctx, policyID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByPolicyID", reflect.TypeOf((*MockRoles)(nil).SelectByPolicyID), ctx, policyID, input)
}

// SelectByUserID mocks base method.
func (m *MockRoles) SelectByUserID(ctx context.Context, userID uuid.UUID, input *domain.SelectRolesInput) (*domain.SelectRolesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByUserID", ctx, userID, input)
	ret0, _ := ret[0].(*domain.SelectRolesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByUserID indicates an expected call of SelectByUserID.
func (mr *MockRolesMockRecorder) SelectByUserID(ctx, userID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByUserID", reflect.TypeOf((*MockRoles)(nil).SelectByUserID), ctx, userID, input)
}

// UnlinkPolicies mocks base method.
func (m *MockRoles) UnlinkPolicies(ctx context.Context, input *domain.UnlinkPoliciesFromRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkPolicies", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkPolicies indicates an expected call of UnlinkPolicies.
func (mr *MockRolesMockRecorder) UnlinkPolicies(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkPolicies", reflect.TypeOf((*MockRoles)(nil).UnlinkPolicies), ctx, input)
}

// UnlinkUsers mocks base method.
func (m *MockRoles) UnlinkUsers(ctx context.Context, input *domain.UnlinkUsersFromRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkUsers", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkUsers indicates an expected call of UnlinkUsers.
func (mr *MockRolesMockRecorder) UnlinkUsers(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkUsers", reflect.TypeOf((*MockRoles)(nil).UnlinkUsers), ctx, input)
}

// UpdateByID mocks base method.
func (m *MockRoles) UpdateByID(ctx context.Context, input *domain.UpdateRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockRolesMockRecorder) UpdateByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockRoles)(nil).UpdateByID), ctx, input)
}
