// Code generated by MockGen. DO NOT EDIT.
// Source: throttle.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/throttle.go -source=throttle.go Throttle
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockThrottle is a mock of Throttle interface.
type MockThrottle struct {
	ctrl     *gomock.Controller
	recorder *MockThrottleMockRecorder
	isgomock struct{}
}

// MockThrottleMockRecorder is the mock recorder for MockThrottle.
type MockThrottleMockRecorder struct {
	mock *MockThrottle
}

// NewMockThrottle creates a new mock instance.
func NewMockThrottle(ctrl *gomock.Controller) *MockThrottle {
	mock := &MockThrottle{ctrl: ctrl}
	mock.recorder = &MockThrottleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThrottle) EXPECT() *MockThrottleMockRecorder {
	return m.recorder
}

// Attempt mocks base method.
func (m *MockThrottle) Attempt(key string) (time.Duration, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attempt", key)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Attempt indicates an expected call of Attempt.
func (mr *MockThrottleMockRecorder) Attempt(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attempt", reflect.TypeOf((*MockThrottle)(nil).Attempt), key)
}

// Succeed mocks base method.
func (m *MockThrottle) Succeed(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Succeed", key)
}

// Succeed indicates an expected call of Succeed.
func (mr *MockThrottleMockRecorder) Succeed(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Succeed", reflect.TypeOf((*MockThrottle)(nil).Succeed), key)
}
