// Code generated by MockGen. DO NOT EDIT.
// Source: users.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/users.go -source=users.go Users
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUsers is a mock of Users interface.
type MockUsers struct {
	ctrl     *gomock.Controller
	recorder *MockUsersMockRecorder
	isgomock struct{}
}

// MockUsersMockRecorder is the mock recorder for MockUsers.
type MockUsersMockRecorder struct {
	mock *MockUsers
}

// NewMockUsers creates a new mock instance.
func NewMockUsers(ctrl *gomock.Controller) *MockUsers {
	mock := &MockUsers{ctrl: ctrl}
	mock.recorder = &MockUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsers) EXPECT() *MockUsersMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockUsers) DeleteByID(ctx context.Context, input *domain.DeleteUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockUsersMockRecorder) DeleteByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockUsers)(nil).DeleteByID), ctx, input)
}

// Insert mocks base method.
func (m *MockUsers) Insert(ctx context.Context, input *domain.InsertUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockUsersMockRecorder) Insert(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockUsers)(nil).Insert), ctx, input)
}

// LinkProjects mocks base method.
func (m *MockUsers) LinkProjects(ctx context.Context, input *domain.LinkProjectsToUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkProjects", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkProjects indicates an expected call of LinkProjects.
func (mr *MockUsersMockRecorder) LinkProjects(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkProjects", reflect.TypeOf((*MockUsers)(nil).LinkProjects), ctx, input)
}

// LinkRoles mocks base method.
func (m *MockUsers) LinkRoles(ctx context.Context, input *domain.LinkRolesToUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkRoles", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkRoles indicates an expected call of LinkRoles.
func (mr *MockUsersMockRecorder) LinkRoles(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkRoles", reflect.TypeOf((*MockUsers)(nil).LinkRoles), ctx, input)
}

// Select mocks base method.
func (m *MockUsers) Select(ctx context.Context, input *domain.SelectUsersInput) (*domain.SelectUsersOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, input)
	ret0, _ := ret[0].(*domain.SelectUsersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockUsersMockRecorder) Select(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockUsers)(nil).Select), ctx, input)
}

// SelectAuthz mocks base method.
func (m *MockUsers) SelectAuthz(ctx context.Context, userID uuid.UUID) (*domain.SelectAuthzOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAuthz", ctx, userID)
	ret0, _ := ret[0].(*domain.SelectAuthzOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAuthz indicates an expected call of SelectAuthz.
func (mr *MockUsersMockRecorder) SelectAuthz(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAuthz", reflect.TypeOf((*MockUsers)(nil).SelectAuthz), ctx, userID)
}

// SelectByEmail mocks base method.
func (m *MockUsers) SelectByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByEmail indicates an expected call of SelectByEmail.
func (mr *MockUsersMockRecorder) SelectByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByEmail", reflect.TypeOf((*MockUsers)(nil).SelectByEmail), ctx, email)
}

// SelectByID mocks base method.
func (m *MockUsers) SelectByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByID indicates an expected call of SelectByID.
func (mr *MockUsersMockRecorder) SelectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByID", reflect.TypeOf((*MockUsers)(nil).SelectByID), ctx, id)
}

// SelectByProjectID mocks base method.
func (m *MockUsers) SelectByProjectID(ctx context.Context, projectID uuid.UUID, input *domain.SelectUsersInput) (*domain.SelectUsersOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByProjectID", ctx, projectID, input)
	ret0, _ := ret[0].(*domain.SelectUsersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByProjectID indicates an expected call of SelectByProjectID.
func (mr *MockUsersMockRecorder) SelectByProjectID(ctx, projectID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByProjectID", reflect.TypeOf((*MockUsers)(nil).SelectByProjectID), ctx, projectID, input)
}

// SelectByRoleID mocks base method.
func (m *MockUsers) SelectByRoleID(ctx context.Context, roleID uuid.UUID, input *domain.ListUsersInput) (*domain.ListUsersOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByRoleID", ctx, roleID, input)
	ret0, _ := ret[0].(*domain.ListUsersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByRoleID indicates an expected call of SelectByRoleID.
func (mr *MockUsersMockRecorder) SelectByRoleID(ctx, roleID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByRoleID", reflect.TypeOf((*MockUsers)(nil).SelectByRoleID), ctx, roleID, input)
}

// UnlinkProjects mocks base method.
func (m *MockUsers) UnlinkProjects(ctx context.Context, input *domain.UnlinkProjectsFromUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkProjects", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkProjects indicates an expected call of UnlinkProjects.
func (mr *MockUsersMockRecorder) UnlinkProjects(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkProjects", reflect.TypeOf((*MockUsers)(nil).UnlinkProjects), ctx, input)
}

// UnlinkRoles mocks base method.
func (m *MockUsers) UnlinkRoles(ctx context.Context, input *domain.UnlinkRolesFromUsersInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkRoles", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkRoles indicates an expected call of UnlinkRoles.
func (mr *MockUsersMockRecorder) UnlinkRoles(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkRoles", reflect.TypeOf((*MockUsers)(nil).UnlinkRoles), ctx, input)
}

// UpdateByID mocks base method.
func (m *MockUsers) UpdateByID(ctx context.Context, input *domain.UpdateUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockUsersMockRecorder) UpdateByID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockUsers)(nil).UpdateByID), ctx, input)
}
