// Code generated by MockGen. DO NOT EDIT.
// Source: users_identities.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../../../../mocks/service/users_identities.go -source=users_identities.go UsersIdentities
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/slashdevops/go-rest-api-service-template/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUsersIdentities is a mock of UsersIdentities interface.
type MockUsersIdentities struct {
	ctrl     *gomock.Controller
	recorder *MockUsersIdentitiesMockRecorder
	isgomock struct{}
}

// MockUsersIdentitiesMockRecorder is the mock recorder for MockUsersIdentities.
type MockUsersIdentitiesMockRecorder struct {
	mock *MockUsersIdentities
}

// NewMockUsersIdentities creates a new mock instance.
func NewMockUsersIdentities(ctrl *gomock.Controller) *MockUsersIdentities {
	mock := &MockUsersIdentities{ctrl: ctrl}
	mock.recorder = &MockUsersIdentitiesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersIdentities) EXPECT() *MockUsersIdentitiesMockRecorder {
	return m.recorder
}

// Link mocks base method.
func (m *MockUsersIdentities) Link(ctx context.Context, input *domain.LinkUserIdentityInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Link", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Link indicates an expected call of Link.
func (mr *MockUsersIdentitiesMockRecorder) Link(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Link", reflect.TypeOf((*MockUsersIdentities)(nil).Link), ctx, input)
}

// SelectBySubject mocks base method.
func (m *MockUsersIdentities) SelectBySubject(ctx context.Context, idpID uuid.UUID, subject string) (*domain.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBySubject", ctx, idpID, subject)
	ret0, _ := ret[0].(*domain.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectBySubject indicates an expected call of SelectBySubject.
func (mr *MockUsersIdentitiesMockRecorder) SelectBySubject(ctx, idpID, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBySubject", reflect.TypeOf((*MockUsersIdentities)(nil).SelectBySubject), ctx, idpID, subject)
}

// SelectByUserID mocks base method.
func (m *MockUsersIdentities) SelectByUserID(ctx context.Context, userID uuid.UUID) ([]domain.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByUserID indicates an expected call of SelectByUserID.
func (mr *MockUsersIdentitiesMockRecorder) SelectByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByUserID", reflect.TypeOf((*MockUsersIdentities)(nil).SelectByUserID), ctx, userID)
}

// Unlink mocks base method.
func (m *MockUsersIdentities) Unlink(ctx context.Context, input *domain.UnlinkUserIdentityInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlink", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlink indicates an expected call of Unlink.
func (mr *MockUsersIdentitiesMockRecorder) Unlink(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlink", reflect.TypeOf((*MockUsersIdentities)(nil).Unlink), ctx, input)
}
